AWSTemplateFormatVersion: '2010-09-09'
Description: "AWS Marketplace SaaS entitlement and subscription portal (qs-1s3j136e1)"
Metadata:
  QuickStartDocumentation:
    EntrypointName: "Deploy AWS Marketplace SaaS entitlement and subscription portal"
  AWS::CloudFormation::Interface:
    ParameterLabels:
      EntitlementSNSTopic:
        default: "Entitlements SNS topic ARN"
      MarketplaceTechAdminEmail:
        default: "Admin email address"
      ProductId:
        default: "Product Id"
      SubscriptionSNSTopic:
        default: "Subscriptions SNS topic ARN"
      PricingModel:
        default: "Pricing model"
      # AWS IA configuration
      ArtifactBucketName:
        default: Artifact S3 bucket name
    ParameterGroups:
      - Label: 
          default: Integration configurations
        Parameters:
          - PricingModel
          - ProductId
          - MarketplaceTechAdminEmail
      - Label: 
          default: Quick Starts Parameters (Do not change)
        Parameters:
           - ArtifactBucketName   
           - SNSAccountID
           - SNSRegion
           - UpdateFulfillmentURL
Parameters:

  # Integration and Automation location parameters
  ArtifactBucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Staging bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Default: aws-quickstart
    # TODO: nitpick the name and wording here
    Description: Name of the S3 bucket name that contains the SAM artifacts. This parameter should not be changed if using the Quick Start solution. Doing so will cause the deployment to fail.
    Type: String
  PricingModel:
    Description: "The pricing model that you choose determines how buyers are able to purchase your product. Ths value should match the price model you selected when creating your listing."
    Type: String
    Default: Contract-based-pricing
    AllowedValues:
    - Contract-with-consumption
    - Contract-based-pricing
    - Usage-based-pricing
  SNSAccountID:
    Type: String
    Default: '287250355862'
    Description: This is the AWS account hosting the SNS Entitlement and Subscription
      topics for your product.
    AllowedValues:
    - '287250355862'
  SNSRegion:
    Type: String
    Default: us-east-1
    Description: This is the AWS region of the SNS Entitlement and Subscription topics
      for your product.
    AllowedValues:
    - us-east-1
  ProductId:
    Description: "Provide the product id for your listing. You can find the product id in the 'Product summary' section for your listing in the AWS Marketplace Management Portal."
    Type: String
    AllowedPattern: .*
  MarketplaceTechAdminEmail:
    Description: "Provide the email address that will receive notifications for new customer registrations, entitlement changes, and subscription events."
    Type: String
    AllowedPattern: .*
  UpdateFulfillmentURL:
    Default: "false"
    Type: String
    Description: "WARNING: This will update your product's fulfillment URL automatically. Be careful if your product is already public"
    AllowedValues:
      - "true"
      - "false"

Mappings:
  PricingModelMap:
    Usage-based-pricing:
      PricingOption: subscriptions
    Contract-based-pricing:
      PricingOption: contracts
    Contract-with-consumption:
      PricingOption: contracts_with_subscription

Resources:
  SampleApp:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${ArtifactBucketName}.s3.amazonaws.com/cloudformation-aws-marketplace-saas/submodules/sam/packaged.yaml"
      Parameters:
        WebsiteS3BucketName:
         !Join
          - '-'
          - - 'web'
            - !Select 
              - 0
              - !Split 
                - "-"
                - !Select
                  - 2
                  - !Split
                    - "/"
                    - !Ref AWS::StackId
        NewSubscribersTableName:
          !Join
            - '-'
            - - 'NewSubscribers'
              - !Select 
                - 0
                - !Split 
                  - "-"
                  - !Select
                    - 2
                    - !Split
                      - "/"
                      - !Ref AWS::StackId
        AWSMarketplaceMeteringRecordsTableName: 
          !Join
            - '-'
            - - 'AWSMarketplaceMeteringRecords'
              - !Select 
                - 0
                - !Split 
                  - "-"
                  - !Select
                    - 2
                    - !Split
                      - "/"
                      - !Ref AWS::StackId
        TypeOfSaaSListing: !FindInMap  
          - PricingModelMap
          - !Ref PricingModel
          - PricingOption  
        SNSAccountID: !Ref SNSAccountID
        SNSRegion: !Ref SNSRegion
        ProductId: !Ref ProductId
        MarketplaceTechAdminEmail: !Ref MarketplaceTechAdminEmail
        CreateCrossAccountRole: 'false'
        CrossAccountId: ''
        CrossAccountRoleName: ''
        MarketplaceSellerEmail: ''
        CreateRegistrationWebPage: 'true'
        UpdateFulfillmentURL: !Ref UpdateFulfillmentURL

Outputs:
  WebsiteS3Bucket:
    Description: This is the bucket for hosting the static site. Retrieve and upload the web files
      at https://github.com/aws-samples/aws-marketplace-serverless-saas-integration/tree/master/web.
    Value: !GetAtt SampleApp.Outputs.WebsiteS3Bucket
  LandingPagePreviewURL:
    Description: Use this URL to preview your landing page. This is NOT the Fulfillment URL.
      for your product.
    Value: !GetAtt SampleApp.Outputs.LandingPagePreviewURL
  AWSMarketplaceFulfillmentURL:
    Description: This is the AWS Marketplace fulfillment URL. Update the "Default fulfillment URL" for you listing with this value.
    Value: !GetAtt SampleApp.Outputs.MarketplaceFulfillmentURL
