AWSTemplateFormatVersion: '2010-09-09'
Description: "AWS Marketplace SaaS entitlement and subscription portal (qs-1s3j136e1)"
Metadata:
  QuickStartDocumentation:
    EntrypointName: "Deploy AWS Marketplace SaaS entitlement and subscription portal"
  AWS::CloudFormation::Interface:
    ParameterLabels:
      AWSMarketplaceMeteringRecordsTableName:
        default: "Metering records Amazon DynamoDB table name"
      CreateRegistrationWebPage:
        default: "Registration page"
      EntitlementSNSTopic:
        default: "Entitlements SNS topic ARN"
      MarketplaceTechAdminEmail:
        default: "Admin email address"
      NewSubscribersTableName:
        default: "New subscribers DynamoDB table name"
      ProductCode:
        default: "Product code"
      SubscriptionSNSTopic:
        default: "Subscriptions SNS topic ARN"
      TypeOfSaaSListing:
        default: "SaaS pricing model"
      WebsiteS3BucketName:
        default: "S3 bucket name"
      # AWS IA configuration
      ArtifactBucketName:
        default: Artifact S3 bucket name


    ParameterGroups:
      - Label: 
          default: AWS Integration and Automation configuration
        Parameters:
          - TypeOfSaaSListing
          - CreateRegistrationWebPage
          - WebsiteS3BucketName
          - ProductCode
          - SubscriptionSNSTopic
          - EntitlementSNSTopic
          - NewSubscribersTableName
          - AWSMarketplaceMeteringRecordsTableName
          - MarketplaceTechAdminEmail
      - Label: 
          default: Quick Starts Parameters (Do not change)
        Parameters:
           - ArtifactBucketName          
Parameters:

  # Integration and Automation location parameters
  ArtifactBucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Staging bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Default: aws-quickstart
    # TODO: nitpick the name and wording here
    Description: Name of the S3 bucket name that contains the SAM artifacts. This parameter should not be changed if using the Quick Start solution. Doing so will cause the deployment to fail.
    Type: String

  WebsiteS3BucketName:
    Type: String
    Description: "The S3 bucket that holds the static HTML registration page files. The bucket name must follow S3 recommendations https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html"
    Default: ''
  NewSubscribersTableName:
    Description: "The custom value for the New Subscribers table. Value must be unique per product."
    Type: String
    AllowedPattern: .*
    Default: AWSMarketplaceSubscribers
  AWSMarketplaceMeteringRecordsTableName:
    Description: "Custom value for the metering records table. Value must be unique per product."
    Type: String
    AllowedPattern: .*
    Default: AWSMarketplaceMeteringRecords
  TypeOfSaaSListing:
    Description: "The SaaS pricing model of your product."
    Type: String
    Default: contracts_with_subscription
    AllowedValues:
    - contracts_with_subscription
    - contracts
    - subscriptions
  SNSAccountID:
    Type: String
    Default: '287250355862'
    Description: This is the AWS account hosting the SNS Entitlement and Subscription
      topics for your product.
    AllowedValues:
    - '287250355862'
  SNSRegion:
    Type: String
    Default: us-east-1
    Description: This is the AWS region of the SNS Entitlement and Subscription topics
      for your product.
    AllowedValues:
    - us-east-1
  ProductCode:
    Description: "The product code provided by AWS Marketplace at the time the limited listing was published."
    Type: String
    AllowedPattern: .*
  MarketplaceTechAdminEmail:
    Description: "The email address that receives SNS notifications for new customer registrations, entitlement changes, and subscription events."
    Type: String
    AllowedPattern: .*
  MarketplaceSellerEmail:
    Type: String
    AllowedPattern: .*
    Default: ''
  CreateCrossAccountRole:
    Default: 'false'
    Description: Do you intend to use cross account access with this integration core?
    Type: String
    AllowedValues:
    - 'true'
    - 'false'
  CrossAccountId:
    Default: ''
    Description: Enter the cross AWS account id
    Type: String
  CrossAccountRoleName:
    Type: String
    Description: 'Your Role Name (ex: OrganizationAccountAccessRole); This will need
      to be the same across all of the Member Accounts'
  CreateRegistrationWebPage:
    Description: "Choose 'true' to create a new registration page hosted by Amazon CloudFront. If you already have a custom registration page, choose 'false'."
    Default: 'true'
    Type: String
    AllowedValues:
    - 'true'
    - 'false'







Conditions:
  CreateRegistrationWebPageCond: !Equals
    - !Ref CreateRegistrationWebPage
    - true







Resources:
  SampleApp:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://packaging-bucket-13a87d77.s3.amazonaws.com/packaged.yaml"
      Parameters:
        WebsiteS3BucketName: !If [CreateRegistrationWebPageCond, !Ref WebsiteS3BucketName, !Ref AWS::NoValue]
        NewSubscribersTableName: !Ref NewSubscribersTableName
        AWSMarketplaceMeteringRecordsTableName: !Ref AWSMarketplaceMeteringRecordsTableName
        TypeOfSaaSListing: !Ref TypeOfSaaSListing
        SNSAccountID: !Ref SNSAccountID
        SNSRegion: !Ref SNSRegion
        ProductCode: !Ref ProductCode
        MarketplaceTechAdminEmail: !Ref MarketplaceTechAdminEmail
        MarketplaceSellerEmail: !Ref MarketplaceSellerEmail
        CreateCrossAccountRole: !Ref CreateCrossAccountRole
        CrossAccountId: !Ref CrossAccountId
        CrossAccountRoleName: !Ref rossAccountRoleName
        CreateRegistrationWebPage: !Ref CreateRegistrationWebPage
Outputs:
  CrossAccountRole:
    Description: This is the cross account role ARN.
    Value: !GetAtt SampleApp.Outputs.CrossAccountRole

  WebsiteS3Bucket:
    Description: S3 bucket for hosting the static site. You can retrieve the files
      at https://github.com/aws-samples/aws-marketplace-serverless-saas-integration/tree/master/web.
    Value: !GetAtt SampleApp.Outputs.WebsiteS3Bucket
  LandingPagePreviewURL:
    Description: URL to preview your landing page. This is NOT the Fulfillment URL
      for your product.
    Value: !GetAtt SampleApp.Outputs.LandingPagePreviewURL
  MarketplaceFulfillmentURL:
    Description: This is the Marketplace fulfillment URL.
    Value: !GetAtt SampleApp.Outputs.MarketplaceFulfillmentURL
